conditioning:
  method: ps
  params:
    scale: 0.5

data:
  name: ffhq #imagenet #ffhq
  root: ./data/demo/
  #root: ./data/demo_remain2/
  #root: ./data/rip_imagenet/ 

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: box
    mask_len_range: !!python/tuple [128, 129]  # for box
    #mask_prob_range: !!python/tuple [0.7, 0.71]  # for random
    image_size: 256


  noise:
    name: gaussian
    sigma: 0.05
    #sigma: 0.05
