conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  #root: ./data/check_SR2/
  #root: ./data/demo/
  root: ./data/demo_remain2/
  #root: ./data/imagenet/

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4
  
  noise: 
    name: gaussian
    sigma: 0.05
#   noise: 
#     name: poisson #gaussian
#     rate: 5
